kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vsphere-01
  namespace: default
spec:
  storageClassName: dr-tanzu-storage-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

