kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres-pxd
  namespace: default
spec:
  storageClassName: pxd-repl3-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
