global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '[REDACTED]'
  smtp_from: '[REDACTED]'
  smtp_auth_username: '[REDACTED]'
  smtp_auth_password: '[REDACTED]'
route:
  group_by: ['alertname']
  # Send all notifications to me.
  receiver: 'email-me'
receivers:
- name: 'email-me'
  email_configs:
  - to: 'testcoadmin@testcolab.com'
    from: 'k8sadmin@testcolab.com'
    smarthost: '[REDACTED]'
    auth_username: '[REDACTED]'
    auth_identity: '[REDACTED]'
    auth_password: '[REDACTED]'
