apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: portworx
  labels:
    prometheus: portworx
spec:
  selector:
    matchLabels:
      name: node-exporter
  endpoints:
  - port: node-exporter