# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.27.9&ns=portworx&b=true&iop=6&s=%22type%3Dgp2%2Csize%3D150%22%2C%22type%3Dgp3%2Csize%3D32%2Ciops%3D450%2Cthroughput%3D125%22&j=auto&c=px-cluster-15a524d3-b61b-4bf4-b634-d69b369e9b54&eks=true&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-15a524d3-b61b-4bf4-b634-d69b369e9b54
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.27.9&ns=portworx&b=true&iop=6&s=%22type%3Dgp2%2Csize%3D150%22%2C%22type%3Dgp3%2Csize%3D32%2Ciops%3D450%2Cthroughput%3D125%22&j=auto&c=px-cluster-15a524d3-b61b-4bf4-b634-d69b369e9b54&eks=true&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
    portworx.io/is-eks: "true"
spec:
  image: portworx/oci-monitor:3.0.4
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - type=gp2,size=150
    - kvdbDeviceSpec: type=gp3,size=32,iops=450,throughput=125
    journalDeviceSpec: auto
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
