apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: dr-apps-01
  namespace: dr-01
spec:
  distribution:
    version: v1.23.8
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: dr-tanzu-storage-01 
    workers:
      count: 4
      class: best-effort-medium
      storageClass: dr-tanzu-storage-01
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 32Gi
